=== SystemsInMotion/Prog-Lang-Eval/assets/xml/tests/progLangEvalTestData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.systemsinmotion.com/hiring/technical/progLangEvalTestData.xsd" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ple="http://www.systemsinmotion.com/hiring/technical/progLangEvalTestData.xsd">

    <element name="test" type="ple:test"></element>
    
    <complexType name="test">
    	<sequence>
    		<element name="intro" type="string"></element>
    		<element name="questions" type="ple:questions"></element>
    	</sequence>
    	<attribute name="type" type="string" use="required"></attribute>
    	<attribute name="id" type="string" use="required"></attribute>
    </complexType>

    <complexType name="questions">
    	<sequence>
    		<element name="question" type="ple:question"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="question">
    	<sequence>
    		<element name="text" type="ple:text" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="answers" type="ple:answers" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="level" type="int" use="required"></attribute>
    </complexType>

    <complexType name="answers">
    	<sequence>
    		<element name="answer" type="ple:answer" minOccurs="2"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="answer">
    	<complexContent>
    		<extension base="ple:text">
    			<attribute name="correct" type="boolean"></attribute>
    			<attribute name="id" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
    

    <complexType name="text" mixed="true">
    	<sequence>
    		<any minOccurs="0" maxOccurs="unbounded" processContents="lax"></any>
    	</sequence>
    </complexType>
</schema>

=== SystemsInMotion/Prog-Lang-Eval/assets/xml/tests/java_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<ple:test id="java_1.0" type="Java"
	xmlns:ple="http://www.systemsinmotion.com/hiring/technical/progLangEvalTestData.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.systemsinmotion.com/hiring/technical/progLangEvalTestData.xsd assets/xml/tests/progLangEvalTestData.xsd ">

	<ple:intro>
		Hi!
		
		You're about to take our Java test! It's not a super long test, but Java's a big langauge so we cover a lot of different topics.
		
		Don't worry; we're not going to make any decisions based on this test alone. It just gives us a way to get an idea how much Java you know so we can make the best decision about where you might fit in our company.
		
		Please take careful note of the grading guidelines. They are available to look at any time.
		The important thing to remember is that while you want to answer as many questions as you can, if you really don't know, that's fine. Just leave it blank and it won't count against you.
	</ple:intro>
	
	<ple:questions>
		<ple:question id="1">
			<ple:text>When comparing two String variables, what will the '==' operator do?</ple:text>

			<ple:answers>
				<ple:answer id="01">Compare the strings case-sensitive and return true if they are the same sequence of characters.</ple:answer>
				<ple:answer id="02">Compare the strings case-insensitive and return true if they are the same sequence of characters.</ple:answer>
				<ple:answer id="03" correct="true">Compare the object references of the strings to see if they are identical.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="2">
			<ple:text>
				What is the output of this code segment?
				<code> 
int i = 0;
System.out.println("value: " + i++);
				</code>
			</ple:text>

			<ple:answers>
				<ple:answer id="04" correct="true"> value: 0</ple:answer>
				<ple:answer id="05">value: 1</ple:answer>
				<ple:answer id="06">value: 2</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="3">
			<ple:text>Which are valid ways to create a new string Object?</ple:text>

			<ple:answers>
				<ple:answer id="07">String strNew;</ple:answer>
				<ple:answer id="08" correct="true">String strNew = "hello";</ple:answer>
				<ple:answer id="09" correct="true">String strNew = new String("hey");</ple:answer>
				<ple:answer id="0A" correct="true">String strNew = new String();</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="4">
			<ple:text>Given a method: protected void foo(), which classes will have access to it?</ple:text>

			<ple:answers>
				<ple:answer id="0B">Any class in the project.</ple:answer>
				<ple:answer id="0C" correct="true">Any class in the same package.</ple:answer>
				<ple:answer id="0D">Only the class it is contained in.</ple:answer>
				<ple:answer id="0E">Only the classes within the defined security specification.</ple:answer>
				<ple:answer id="0F" correct="true">Any subclass of the class it is contained in.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="5">
			<ple:text>Which statements are true about the value of a variable, when no explicit assignments have been made?</ple:text>

			<ple:answers>
				<ple:answer id="10">The value of a variable of type int is undetermined.</ple:answer>
				<ple:answer id="11" correct="true">The value of a variable of any numeric type is zero.</ple:answer>
				<ple:answer id="12">The compiler may issue an error if the variable is used in a method before it is initialized.</ple:answer>
				<ple:answer id="13">A variable of type String will denote the empty String("")</ple:answer>
				<ple:answer id="14" correct="true">The value of all variables which are references is null.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="6">
			<ple:text>In Java's object model, a class can have multiple ______ but only a single direct ______</ple:text>

			<ple:answers>
				<ple:answer id="15">Interfaces, child</ple:answer>
				<ple:answer id="16">Children, parent</ple:answer>
				<ple:answer id="17" correct="true">Interfaces, parent</ple:answer>
				<ple:answer id="18">Parents, interface</ple:answer>
				<ple:answer id="19">None of the above.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="7">
			<ple:text>Which statements describe guaranteed behavior of the garbage collection and finalization mechanisms?</ple:text>

			<ple:answers>
				<ple:answer id="1A">An object is deleted as soon as there are no more references that denote the object.</ple:answer>
				<ple:answer id="1B">The finalize() method will eventually be called on every object.</ple:answer>
				<ple:answer id="1C" correct="true">The finalize() method will never be called more than once on an object.</ple:answer>
				<ple:answer id="1D" correct="true">An object will not be garbage collected as long as it is possible for a thread to access it through a reference.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="8">
			<ple:text>Which statement is true?</ple:text>

			<ple:answers>
				<ple:answer id="1E">Top-level classes can be declared static.</ple:answer>
				<ple:answer id="1F" correct="true">Classes declared as members of top-level classes can be declared static.</ple:answer>
				<ple:answer id="20">Local classes can be declared static.</ple:answer>
				<ple:answer id="21">Anonymous classes can be declared static.</ple:answer>
				<ple:answer id="22">NO classes can be declared static.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="9">
			<ple:text>Which statements are true?</ple:text>

			<ple:answers>
				<ple:answer id="23" correct="true">No other static members, except final static fields, can be declared within a non-static member class.</ple:answer>
				<ple:answer id="24">If a non-static member class is nested within a class named Outer, then methods within the non-static member class must use the prefix Outer.this</ple:answer>
				<ple:answer id="25">All fields in any nested class must be declared final.</ple:answer>
				<ple:answer id="26" correct="true">Anonymous classes cannot have constructors.</ple:answer>
				<ple:answer id="27">If objRef is an instance of any nested class within the class Outer, then the expression (objRef instanceOf Outer) will evaluate to true.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="10">
			<ple:text>
				Which statements are true about the relationships between the following classes?
		
				<code>
class Foo {
	int num;
	Baz comp = new Baz();
}
	
class Bar {
	boolean flag;
}

class Baz extends Foo {
	Bar thing = new Bar();
	double limit;
}
				</code>
			</ple:text>

			<ple:answers>
				<ple:answer id="28">A Bar is a Baz.</ple:answer>
				<ple:answer id="29" correct="true">A Foo has a Bar.</ple:answer>
				<ple:answer id="2A" correct="true">A Baz is a Foo.</ple:answer>
				<ple:answer id="2B">A Foo is a Baz.</ple:answer>
				<ple:answer id="2C" correct="true">A Baz has a Bar.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="11">
			<ple:text>Which statement is true?</ple:text>

			<ple:answers>
				<ple:answer id="2D">If an exception is thrown during the execution of the finalize() method of an eligible object then the exception is ignored and the object is destroyed</ple:answer>
				<ple:answer id="2E" correct="true">All objects have a finalize() method.</ple:answer>
				<ple:answer id="2F">Objects can be destroyed by explicitly calling the finalize() method.</ple:answer>
				<ple:answer id="30">The finalize() method can be declared with any accessibility.</ple:answer>
				<ple:answer id="31">The compiler will fail to compile code that defines an overriding finalize() method</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="12">
			<ple:text>Which statements are true?</ple:text>

			<ple:answers>
				<ple:answer id="32">If an exception is not caught in a method, the method will terminate and normal execution will resume.</ple:answer>
				<ple:answer id="33">An overriding method must declare that it throws the same exception classes as the method it overrides.</ple:answer>
				<ple:answer id="34" correct="true">The main() method of a program can declare that it throws checked exceptions.</ple:answer>
				<ple:answer id="35" correct="true">A method declaring that it throws a certain exception class may throw instances of any subclass of that exception class.</ple:answer>
				<ple:answer id="36">Finally blocks are executed if, and only if, an exception gets thrown while inside the corresponding try block.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="13">
			<ple:text>
				What will be the result of attempting to compile and run the following program?
		
				<code>
public class MyClass {
	public static void main(String[] args) {
		RuntimeException re = null;
	throw re;
	}
}
				</code>
		  	</ple:text>

			<ple:answers>
				<ple:answer id="37">The code will fail to compile, because main() does not declare that it throws a RuntimeException</ple:answer>
				<ple:answer id="38">The program will fail to compile, since it cannot throw re.</ple:answer>
				<ple:answer id="39">The program will compile without error and will throw a RunTimeException when run.</ple:answer>
				<ple:answer id="3A" correct="true">The program will compile without error and will throw a NullPointerException when run.</ple:answer>
				<ple:answer id="3B">THe program will compile without error and will run and terminate without any output.</ple:answer>
			</ple:answers>
		</ple:question>
		
		<ple:question id="14">
			<ple:text>
				What will the output of this program be?
				<code>
public class MyClass {
 
 	//Assume InterruptedException is a direct subclass of Exception.
	static void f() throws InterruptedException {
		throw new InterruptedException("All your base.");
	}
	
	public static void main( String[] args) {		
		try{
			f();
		} catch (InterruptedException e)	{
